chore: Add xml parser verify-links check
thenativeweb/thenativeweb-ux pull request #781
Opened 2020-11-03 10:47 UTC by dotKuro

Should fix #757

2020-11-03 11:11 UTC, goloroden requested changes
Hi @dotKuro 👋 

This looks good, however, I have a few minor comments.
Can you please have a look at them?

2020-11-03 11:31 UTC, dotKuro commented
Thanks for the quick reply! I fixed the issues now. 👍

2020-11-03 11:59 UTC, dotKuro commented
When I was trying to contribute the correct typing to the @types/xml2js package, as we discussed yesterday, I found that the library has a promise based function as well. I swapped it in instead of using promisify.

2020-11-03 21:05 UTC, goloroden requested changes
Hey @dotKuro 👋 

It's me, once again… I have reviewed your changes, and I still have a few things. But, we're getting closer every time 👍

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +  test('returns all links from the xml file.', async (): Promise<void> => {
I think we should uppercase the file endings in test descriptions, so this should be `XML` (and further down below `TXT`). I will not add a comment for every single test, but I guess you will look through all of them anyway 😊

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +            lastmod: [ '...' ]
Just for information: What would be a reasonable value for this field?

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +      `;
I originally thought that this blank line is not needed – until I read the test description. Maybe we can highlight this a little bit more (although I don't have an idea, how, TBH).

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +  test('parses XML file correctly.', async (): Promise<void> => {
Either `XML files` or `the XML file`, I'd say.

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +    writeFileSync(tempFile, validXMLData);
Can we please replace these `...Sync` calls by their promise-based counterparts from `fs.promises`?

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +  test('throws error on valid xml file with wrong structure.', async (): Promise<void> => {
I'd suggest to add an `an` between `throws` and `error`.

2020-11-03 21:05 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +    assert.that(errorThrown).is.true();
```suggestion
    await assert.that(async (): Promise<void> => {
      await getUrlsFromSitemap({ sitemapPath: tempFile });
    }).is.throwingAsync();
```

2020-11-10 08:14 UTC, dotKuro commented on lib/cli/verifyLinks/getUrlsFromSitemap.ts
> +  type: 'object' as const,
The problem with using `statement as type` is that it will skip the type checking for this type and asserts that it is that type. This will defeat the entire purpose of the library having types all together, because the type is supposed to validate whether or not we wrote a valid (valid in the sense of syntactically valid) JSON schema. Using this might be more annoying but is easier to debug for sure. 

Another solution would be to export constant tokens from the library it self.

in validate-value: 
```typescript
const stringValue = 'string'
const objectValue = 'object'
...



export {
...

  values:  {
    string: stringValue,
    object: objectValue
    ...
  }
}
```

in code:
```typescript
import { Value. values as v} from 'validate-value'

const schema = {
  type: v.object
  properties: { ... }
}

```

2020-11-10 08:21 UTC, dotKuro commented on test/cli/getUrlsFromSitemapTests.ts
> +            lastmod: [ '...' ]
Something like `2020-10-28T16:55:03.554Z` and is generated using `new Date().toISOString()`.

Should I add examples to the tests?

2020-11-10 08:25 UTC, dotKuro commented on test/cli/getUrlsFromSitemapTests.ts
> +      `;
I have no idea how to highlight it either. I personally think it is fine, since it is test data. I think for test data you usually realize rather quickly that stuff that looks fishy tests some weird edge cases.  But maybe that's only for me.

2020-11-10 08:27 UTC, dotKuro commented on test/cli/getUrlsFromSitemapTests.ts
> +      `;
The only thing I could come up with is to replace the trailing newline with `\n` which is the same thing, but avoids that problem. This will be rather inconsistent with the other newlines in the middle of the data though.


Thoughts on that?

2020-11-10 08:58 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +      `;
After having thought about this, let's stick with it in the current way. It becomes clear when one reads the test description.

2020-11-10 09:00 UTC, goloroden commented on test/cli/getUrlsFromSitemapTests.ts
> +            lastmod: [ '...' ]
Yes, we could use an actual value here, to make things more clear. Theoretically, since it doesn't really matter which value is being used, we might actually generate one here on each run of the test.

2020-11-10 09:04 UTC, goloroden commented on lib/cli/verifyLinks/getUrlsFromSitemap.ts
> +  type: 'object' as const,
Hmmm 🤔 

What would you prefer?

2020-11-10 09:22 UTC, dotKuro commented on lib/cli/verifyLinks/getUrlsFromSitemap.ts
> +  type: 'object' as const,
Both pretty much have the same disadvantage unfortunately: You can't just paste a valid JSON schema from somewhere else and have it work with out adjusting it. Ideally we would find a solution that would be able to do that, but for the time being I would prefer the exporting constant tokens variant over the `as const` variant. It is much better to read in my opinion.

2020-11-10 09:24 UTC, goloroden commented on lib/cli/verifyLinks/getUrlsFromSitemap.ts
> +  type: 'object' as const,
Then let's do it like this, using the `values` property. And I like the approach with the alias. 👍

2020-11-12 08:58 UTC, dotKuro commented
Everything should be resolved now 👍

2020-11-12 09:17 UTC, goloroden approved these changes

2020-11-12 09:19 UTC, merged